name: Build and Deploy

on:[push]

env:
  AZURE_WEBBAPP_NAME: "myclobberapi"
  AZURE_WEBBAPP_PACKAGE_PATH: "./published"
  NETCORE_VERSION: "3.1.103"

jobs:
  build_myclobber_api:
    name: "myclobberr.api build & deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net Core SDK ${{env.NETCORE_VERSION}}
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{env.NETCORE_VERSION}}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore c Release

      - name: Assetscreatiopn
        run: dotnet publish --configuration Release --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Deploy to Azure
        run: azure/web-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

